//Automatically generated by file2array

//include guard
#ifndef _font_gohufont_H_
#define _font_gohufont_H_


#define GOHUFONT11_W  6   //glyph width
#define GOHUFONT11_H  11  //glyph height
#define GOHUFONT11_B  8   //baseline offset

//source: "gohufont-11.bmp"  size: 2242
//1 bpp, white glyphs on black bg, monospace 6x11, 0x00-0xff
extern unsigned char gohufont11bmp[2242];


#endif
